const MyProfile = {
    id: 1,
    username: "marksantiago2909",
    email: "marksantiago2909@gmail.com",
    name: "Mark Santiago",
    slug: "marksantiago2909",
    nickname: "marksantiago2909",
    gender: "M",
    image: '/images/Mark.png',
    dob: "string",
    website: "string",
    contact: "string",
    contact_email: "marksantiago2909@gmail.com",
    linkedin: "https://www.linkedin.com/in/m-lovern-santiago-a39060386/",
    github: "https://github.com/marksantiago2909",
    address: "Block 9 Lot 16 Coral Street Phase 4 Mansfield Sto. Domingo, Angeles City, Central Luzon, Philippines",
    about: "string",
    is_portfolio_user: "string",
    resume_link: "https://drive.google.com/file/d/1-GRD83e6c5SxR3ScEhtsxHkHz8lPJDTF/view?usp=sharing",
    is_active: "string",
    is_staff: "string",
    is_superuser: "string",
    date_joined: "6 Jul 2024",
    last_login: "6 Jul 2024",
    updated_at: "6 Jul 2024",
};

export default MyProfile;