const Project = [
    {
        id: "1",
        title: "NYW NFT Marketplace",
        slug: "NYWNFTMarketplace",
        image: '/images/Projects/NYWNFT.PNG',
        short_description: "NFT Marketplace",
        technology: "Blockchain, NFT, marketplace, Smart Contract",
        duration: "May 2024 ~ Aug 2024",
        duration_in_days: "4 Months",
        preview_url: "https://nyw-marketplace.vercel.app/",
        github_url: "https://github.com/marksantiago2909/NYW-NFT-frontend",
        description: "New York World NFT is a unique and multi - chain marketplace specializing in super rare NFTs(Non-Fungible Token) and crypto-collectibles",
        created_at: "05 May 2024",
        updated_at: "25 Aug 2024",
    },
    {
        id: "2",
        title: "Vulcan Launchpad",
        slug: "VulcanLaunchpad",
        image: '/images/Projects/vulcan.PNG',
        short_description: "ICO Launchpad",
        technology: "Blockchain, ICO, Launchpad, Smart Contract",
        duration: "May 2023 ~ Oct 2023",
        duration_in_days: "6 Months",
        preview_url: "https://vulcanpad.tech/",
        github_url: "https://github.com/marksantiago2909/SilverPad_Contract",
        description: "Vulcan Launchpad is a Crowd Funding System for multi-chain eco system",
        created_at: "19 May 2023",
        updated_at: "11 Oct 2023",
    },
    {
        id: "3",
        title: "TurboTrade",
        slug: "TurboTrade",
        image: '/images/Projects/turbo.PNG',
        short_description: "A DeFi Platform",
        technology: "Blockchain, NFT, marketplace, Smart Contract",
        duration: "Oct 2023 ~ Mar 2024",
        duration_in_days: "5 Months",
        preview_url: "https://app.turbotrade.tech/",
        github_url: "https://github.com/marksantiago2909/TurboTrade",
        description: "Turbo Trade is a DeFi platform that facilitates easy wallet connectivity, efficient token swapping, and liquidity management.",
        created_at: "25 Oct 2023",
        updated_at: "19 Mar 2024",
    },
    {
        id: "4",
        title: "Xion",
        slug: "Xion",
        image: '/images/Projects/xion.png',
        short_description: "A DeFi Platform",
        technology: "Blockchain, NFT, marketplace, Smart Contract",
        duration: "Oct 2022 ~ Feb 2023",
        duration_in_days: "4 Months",
        preview_url: "https://xion.app/home",
        github_url: "https://github.com/marksantiago2909/xion_finance",
        description: "XION a DeFi Global cross-chain Staking - cryto shopping up to 100% cashback rewards.",
        created_at: "03 Oct 2023",
        updated_at: "23 Feb 2024",
    },
    {
        id: "5",
        title: "QSE Token Presale platform",
        slug: "qse",
        image: '/images/Projects/qse.PNG',
        short_description: "An ERC20 token presale Platform",
        technology: "ERC20, ICO, Presale, Smart Contract",
        duration: "May 2025 ~ Jul 2025",
        duration_in_days: "3 Months",
        preview_url: "https://quantsec.ai",
        github_url: "https://github.com/HCISS-LLC-BSECAEnergy/ICO-Page",
        description: "Quantsec is an ERC20 token presale platform for HCISS Ecosystem",
        created_at: "03 May 2025",
        updated_at: "23 Jul 2025",
    },
    {
        id: "6",
        title: "EventSmarter",
        slug: "EventSmarter",
        image: '/images/Projects/eventsmarter.jpg',
        short_description: "Onsite Event Check-in Software",
        technology: "React, Node.js, MongoDB, Express.js, Socket.io",
        duration: "Aug 2022 ~ Sep 2022",
        duration_in_days: "2 Months",
        preview_url: "https://www.eventssmarter.com/",
        github_url: "https://github.com/marksantiago2909/eventsmarter",
        description: "Events Smarter is a platform designed for the entertainment and event industries that facilitates ticket buying and selling.",
        created_at: "03 Aug 2022",
        updated_at: "29 Sep 2022",
    },
    {
        id: "7",
        title: "Trademark",
        slug: "Trademark",
        image: '/images/Projects/trademark.PNG',
        short_description: "Farm Investment platform",
        technology: "React, Node.js, MongoDB, Express.js, Socket.io",
        duration: "Jul 2021 ~ Sep 2021",
        duration_in_days: "2 Months",
        preview_url: "https://trade-mark-lake.vercel.app/",
        github_url: "https://github.com/marksantiago2909/TradeMark_Next",
        description: "Trade Mark is a platform designed to give investors access to diverse, institutional-quality farm land opportunities.",
        created_at: "04 Jul 2021",
        updated_at: "23 Sep 2021",
    },
    {
        id: "8",
        title: "SailMe",
        slug: "SailMe",
        image: '/images/Projects/sailme.jpg',
        short_description: "Boat Rentals Platform",
        technology: "React, Node.js, MongoDB, Express.js",
        duration: "Feb 2022 ~ Apr 2022",
        duration_in_days: "3 Months",
        preview_url: "https://sailme.com/",
        github_url: "https://github.com/marksantiago2909/sailme",
        description: "SailMe is a growing boat rental marketplace that makes it easy for both boat owners, who want to earn extra money from their boats by renting them out and for boat charter agencies to manage their boats, bookings and messages.",
        created_at: "12 Feb 2022",
        updated_at: "27 Apr 2022",
    },
    {
        id: "9",
        title: "BollyGaming Casino Slot Game",
        slug: "BollyGamingCasinoSlotGame",
        image: '/images/Projects/VVSL.png',
        short_description: "A B2B Casino Game Platform",
        technology: "Casino Game, B2B, Slot Game, React, Pixijs",
        duration: "May 2019 ~ Aug 2019",
        duration_in_days: "4 Months",
        preview_url: "https://lobbyuat.bollygaming.games/slot/mbsl/?token=c42ca54b-0e44-4348-95c5-f0c058334847",
        github_url: "https://github.com/marksantiago2909/Casino_slot",
        description: "A casino slot games for Vampire Vault Theme, Wild West Theme,  using React and Pixijs",
        created_at: "05 May 2019",
        updated_at: "25 Aug 2019",
    },
    {
        id: "10",
        title: "BollyGaming Casino Game",
        slug: "BollyGamingCasinoGame",
        image: '/images/Projects/aviator.png',
        short_description: "A B2B Casino Game Platform",
        technology: "Casino Game, B2B, Slot Game, Aviator, Lucky Wheel, Heads or Tails",
        duration: "Oct 2019 ~ Apr 2020",
        duration_in_days: "6 Months",
        preview_url: "https://lobbyuat.bollygaming.games/aviator/?token=c42ca54b-0e44-4348-95c5-f0c058334847",
        github_url: "https://github.com/marksantiago2909/Casino_slot",
        description: "A casino slot games, aviator, lucky wheel, heads or tails game using React and Pixijs",
        created_at: "05 Oct 2019",
        updated_at: "25 Apr 2020",
    },
    {
        id: "11",
        title: "MiradaAI",
        slug: "MiradaAI",
        image: '/images/Projects/miradaai.PNG',
        short_description: "Decentralized AI Platform",
        technology: "Next.js, FastAPI, OpenAI, LangGraph, DALL-E, Pinecone, Solidity, Ethers.js",
        duration: "Nov 2022  Oct 2023",
        duration_in_days: "10 Months",
        preview_url: "https://mirada.ai/",
        github_url: "https://github.com/cycle-sync-ai/mirada-ai-tech-report",
        description: "Mirada AI leverages blockchain technology to democratize AI, making image generation, LLM chat, search, and more accessible to all.",
        created_at: "05 Nov 2022",
        updated_at: "2 Oct 2023",
    },
    {
        id: "12",
        title: "ChatEss",
        slug: "ChatEss",
        image: '/images/Projects/chatess.jpg',
        short_description: "AI Query and Analytics Platform",
        technology: "SQL Agent, Langchain, Langgraph, Pinecone, Next.js, Typescrpt, D3.js, Websocket, Redis, Celery, Trino",
        duration: "Jul 2025 ~ Oct 2025",
        duration_in_days: "3 Months",
        preview_url: "https://chatess.com/",
        github_url: "https://github.com/bigdata5911/supply-chain-insight-platform",
        description: "ChatEss is an innovative platform designed to enhance customer interactions by seamlessly retrieving information from databases through natural language queries.",
        created_at: "05 Jul 2025",
        updated_at: "25 Oct 2025",
    },
    {
        id: "13",
        title: "Brighter VPN",
        slug: "BrighterVPN",
        image: '/images/Projects/brighter.PNG',
        short_description: "A VPN App",
        technology: "React Native, Typescript, Firebase, Expo, React Native Paper, React Native Vector Icons, React Native Safe Area Context",
        duration: "Oct 2024 ~ Jan 2025",
        duration_in_days: "6 Months",
        preview_url: "https://play.google.com/store/apps/details?id=com.brighter.vpn.app&hl=en",
        github_url: "https://github.com/marksantiago2909/BrighterVPN",
        description: "Bright VPN is a free, secure VPN that encrypts data, hides your IP, and unblocks websites, without needing email or credit card.",
        created_at: "09 Oct 2024",
        updated_at: "24 Jan 2025",
    },
    {
        id: "14",
        title: "Solar Card",
        slug: "SolarCard",
        image: '/images/Projects/solar.PNG',
        short_description: "A Financial Card",
        technology: "Flutter, Dart, Firebase, Stripe, Flutterwave",
        duration: "Jan 2025 ~ Apr 2025",
        duration_in_days: "3 Months",
        preview_url: "https://play.google.com/store/apps/details?id=app.solarcard.ionic&hl=en&pli=1",
        github_url: "https://github.com/marksantiago2909/solar-card",
        description: "The Solar Card is a cutting-edge financial tool designed to seamlessly integrate digital assets into everyday spending.",
        created_at: "05 Jan 2025",
        updated_at: "25 Apr 2025",
    }
];

export default Project;